### ISSUE TITLE
How can I include all types in generated Changelog ?

### ISSUE THREAD

**Issue by asapMaki** [absolute-version/commit-and-tag-version#47] opened 2022-12-06 19:04 UTC
Hi,

I am kind of blocked here and I switched to your package in hope that it has implemented type configuration.

My package.json config is like this:
`
  "commit-and-tag-version": {
    "skip": {
      "commit": true
    },
    "types": [
      {
        "type": "feat",
        "section": "Features:"
      },
      {
        "type": "fix",
        "section": "Bug Fixes"
      },
      {
        "type": "chore",
        "section": "Chore: Maintenance",
        "hidden": false
      },
      {
        "type": "docs",
        "section": "Documentation:",
        "hidden": false
      },
      {
        "type": "style",
        "hidden": false
      },
      {
        "type": "refactor",
        "hidden": false
      },
      {
        "type": "perf",
        "hidden": false
      },
      {
        "type": "test",
        "hidden": false
      }
    ]
  }
`

And it is existing in the official documentation [conventional-changelog-config-spec](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.2.0/README.md#types).

**Comment by TimothyJones** [comment] 2022-12-06 21:53
I’m not 100% clear what you’re asking here- are you saying that the config you’ve listed doesn’t work, or are you saying that you’d like to be able to match “*”?

**Comment by asapMaki** [comment] 2022-12-06 21:59
Sorry for not being clear.
I would like for generated changelog to include other types as well. 
On the left here are my commits, on the right is generated changelog.
It only used feat: type, not docs: testing: , etc


<img width="1081" alt="image" src="https://user-images.githubusercontent.com/30200380/206031588-f1038424-c262-4d30-a5b5-2ab31a49eead.png">

**Comment by TimothyJones** [comment] 2022-12-06 22:29
Hmm. This should work. I’ll take a look.

How are you invoking it? Any arguments?

**Comment by asapMaki** [comment] 2022-12-07 13:32
So by default it didn't work.
I tried passing the configuration as in initial question that I posted, also didn't work.

I am using command `commit-and-tag-version --release-as minor`

I installed it via yarn.
Version is "commit-and-tag-version": "^10.1.0"

**Comment by TimothyJones** [comment] 2022-12-15 02:30
I'm afraid I can't reproduce this. With a repository like so:

```
$ git log --short

6265af4 (HEAD -> main) chore: Add all types of commits to changelog
5bbdaff docs: Update readme
9418e0e feat: Add readme
51ea711 Initial commit
```

and your stanza in package json, I get the correct changelog with `npx commit-and-tag-version --release-as minor`. You can see this with [this repository](https://github.com/TimothyJones/ctv-issue-47), which is in the state before the tag is applied.

I think there's something else going on here. Can you give the example repo I linked a go, and see if you can reproduce the problem you're experiencing?

**Comment by asapMaki** [comment] 2022-12-15 08:37
I tried your repo and it did work, and I wen to my repo as well just to try and figure out the reasons, and I got to the solution.

It had to do with tags and generating the changelog.
Because at the start I created couple of changelogs added some configurations, and was overall playing with this tool.
In that process my commits were tied to the tags, and were skipped in next changelog creation.

Once I deleted tags, there were included in the changelog and used all of those types mentioned above.

Thank you for your responses and help, have a nice day.

**Comment by TimothyJones** [comment] 2022-12-15 09:13
Ah! Yes, it doesn’t generate the entire changelog, it prepends the changes to the top. This is advantageous if you ever need to manually edit it.

I’ll close this for now, please feel free to reopen if you think there are changes that are necessary.

**Closed by TimothyJones** 2022-12-15 09:13 UTC
Labels: question
